# 패키지 설치 모음 : packages
# 라인 실행: CTRL + R

print("패키지 설치 시작")

.libPaths()                #라이브러리 설치 경로 확인
.libPaths("C:/R/library")  #라이브러리 설치 경로 변경

installed.packages()                                      # 설치된 package 보여주기.
installed.packages()[,c("Package","Version")]             # package의 명칭과 버전. 

install.packages("C:/R/library/bindr_0.1.1.zip", repos=NULL)
install.packages("C:/R/library/bindrcpp_0.2.2.zip", repos=NULL)
install.packages("C:/R/library/purrr_0.2.5.zip", repos=NULL)
install.packages("C:/R/library/tidyselect_0.2.5.zip", repos=NULL)
install.packages("C:/R/library/zip_1.0.0.zip", repos=NULL)
install.packages("C:/R/library/bitops_1.0-6.zip", repos=NULL)
install.packages("C:/R/library/NLP_0.2-0.zip", repos=NULL)
install.packages("C:/R/library/slam_0.1-44.zip", repos=NULL)
install.packages("C:/R/library/xml2_1.2.0.zip", repos=NULL)
install.packages("C:/R/library/htmlwidgets_1.3.zip", repos=NULL)

install.packages("C:/R/library/Rcpp_1.0.0.zip", repos=NULL)
install.packages("C:/R/library/readxl_1.2.0.zip", repos=NULL) 
install.packages("C:/R/library/animation_2.6.zip", repos=NULL)
install.packages("C:/R/library/arules_1.6-2.zip", repos=NULL) 
install.packages("C:/R/library/arulesViz_1.3-2.zip", repos=NULL)
install.packages("C:/R/library/devtools_2.0.1.zip", repos=NULL) 
install.packages("C:/R/library/dplyr_0.7.8.zip", repos=NULL)
install.packages("C:/R/library/gtable_0.2.0.zip", repos=NULL)
install.packages("C:/R/library/ggplot2_3.1.0.zip", repos=NULL) 
install.packages("C:/R/library/hash_2.2.6.zip", repos=NULL) 
install.packages("C:/R/library/openxlsx_4.1.0.zip", repos=NULL)
install.packages("C:/R/library/RCurl_1.95-4.11.zip", repos=NULL)
install.packages("C:/R/library/rJava_0.9-10.zip", repos=NULL) 
install.packages("C:/R/library/RSQLite_2.1.1.zip", repos=NULL)
install.packages("C:/R/library/Sejong_0.01.zip", repos=NULL) 
install.packages("C:/R/library/stringr_1.3.1.zip", repos=NULL)
install.packages("C:/R/library/tau_0.0-20.zip", repos=NULL)
install.packages("C:/R/library/tm_0.7-6.zip", repos=NULL) 
install.packages("C:/R/library/wordcloud_2.6.zip", repos=NULL)
install.packages("C:/R/library/wordcloud2_0.2.1.zip", repos=NULL)
install.packages("C:/R/library/XML_3.98-1.16.zip", repos=NULL)
install.packages("C:/R/library/cellranger_1.1.0.zip", repos=NULL)

install.packages("C:/R/library/DBI_1.0.0.zip", repos=NULL)
install.packages("C:/R/library/bit64_0.9-7.zip", repos=NULL)
install.packages("C:/R/library/bit_1.1-14.zip", repos=NULL)
install.packages("C:/R/library/cli_1.0.1.zip", repos=NULL)
install.packages("C:/R/library/assertthat_0.2.0.zip", repos=NULL)
install.packages("C:/R/library/crayon_1.3.4.zip", repos=NULL)
install.packages("C:/R/library/pkgbuild_1.0.2.zip", repos=NULL)
install.packages("C:/R/library/R6_2.3.0.zip", repos=NULL)
install.packages("C:/R/library/callr_3.1.1.zip", repos=NULL)
install.packages("C:/R/library/processx_3.2.1.zip", repos=NULL)
install.packages("C:/R/library/ps_1.3.0.zip", repos=NULL)
install.packages("C:/R/library/magrittr_1.5.zip", repos=NULL)
install.packages("C:/R/library/prettyunits_1.0.2.zip", repos=NULL)
install.packages("C:/R/library/desc_1.2.0.zip", repos=NULL)
install.packages("C:/R/library/pkgload_1.0.2.zip", repos=NULL)
install.packages("C:/R/library/rlang_0.3.0.1.zip", repos=NULL)
install.packages("C:/R/library/rprojroot_1.3-2.zip", repos=NULL)
install.packages("C:/R/library/rstudioapi_0.8.zip", repos=NULL)
install.packages("C:/R/library/withr_2.1.2.zip", repos=NULL)
install.packages("C:/R/library/backports_1.1.3.zip", repos=NULL)
install.packages("C:/R/library/remotes_2.0.2.zip", repos=NULL)
install.packages("C:/R/library/sessioninfo_1.1.1.zip", repos=NULL)
install.packages("C:/R/library/clipr_0.4.1.zip", repos=NULL)
install.packages("C:/R/library/clisymbols_1.2.0.zip", repos=NULL)
install.packages("C:/R/library/curl_3.2.zip", repos=NULL)
install.packages("C:/R/library/fs_1.2.6.zip", repos=NULL)
install.packages("C:/R/library/gh_1.0.1.zip", repos=NULL)
install.packages("C:/R/library/git2r_0.23.0.zip", repos=NULL)
install.packages("C:/R/library/glue_1.3.0.zip", repos=NULL)
install.packages("C:/R/library/usethis_1.4.0.zip", repos=NULL)
install.packages("C:/R/library/stringi_1.2.4.zip", repos=NULL)
install.packages("C:/R/library/digest_0.6.18.zip", repos=NULL)
install.packages("C:/R/library/memoise_1.1.0.zip", repos=NULL)
install.packages("C:/R/library/blob_1.1.1.zip", repos=NULL)
install.packages("C:/R/library/KoNLP_0.80.1.zip", repos=NULL)
install.packages("C:/R/library/tidyverse_1.2.1.zip", repos=NULL)

install.packages("C:/R/library/base64enc_0.1-3.zip", repos=NULL)
install.packages("C:/R/library/BH_1.66.0-1.zip", repos=NULL)
install.packages("C:/R/library/data.table_1.11.8.zip", repos=NULL)
install.packages("C:/R/library/colorspace_1.3-2.zip", repos=NULL)
install.packages("C:/R/library/evaluate_0.12.zip", repos=NULL)
install.packages("C:/R/library/fansi_0.4.0.zip", repos=NULL)
install.packages("C:/R/library/highr_0.7.zip", repos=NULL)
install.packages("C:/R/library/htmltools_0.3.6.zip", repos=NULL)
install.packages("C:/R/library/jsonlite_1.6.zip", repos=NULL)
install.packages("C:/R/library/knitr_1.21.zip", repos=NULL)
install.packages("C:/R/library/labeling_0.3.zip", repos=NULL)
install.packages("C:/R/library/lazyeval_0.2.1.zip", repos=NULL)
install.packages("C:/R/library/markdown_0.9.zip", repos=NULL)
install.packages("C:/R/library/mime_0.6.zip", repos=NULL)
install.packages("C:/R/library/munsell_0.5.0.zip", repos=NULL)
install.packages("C:/R/library/pillar_1.3.1.zip", repos=NULL)
install.packages("C:/R/library/pkgconfig_2.0.2.zip", repos=NULL)
install.packages("C:/R/library/plogr_0.2.0.zip", repos=NULL)
install.packages("C:/R/library/plyr_1.8.4.zip", repos=NULL)

install.packages("C:/R/library/RColorBrewer_1.1-2.zip", repos=NULL)
install.packages("C:/R/library/reshape_0.8.8.zip", repos=NULL)
install.packages("C:/R/library/reshape2_1.4.3.zip", repos=NULL)
install.packages("C:/R/library/rmarkdown_1.11.zip", repos=NULL)
install.packages("C:/R/library/scales_1.0.0.zip", repos=NULL)
install.packages("C:/R/library/testthat_2.0.1.zip", repos=NULL)
install.packages("C:/R/library/tibble_1.4.2.zip", repos=NULL)
install.packages("C:/R/library/tinytex_0.9.zip", repos=NULL)
install.packages("C:/R/library/utf8_1.1.4.zip", repos=NULL)
install.packages("C:/R/library/viridisLite_0.3.0.zip", repos=NULL)
install.packages("C:/R/library/xfun_0.4.zip", repos=NULL)
install.packages("C:/R/library/yaml_2.2.0.zip", repos=NULL)

installed.packages()                                      # 설치된 package 보여주기.
installed.packages()[,c("Package","Version")]             # package의 명칭과 버전. 


# 패키지 메모리로 불러오기 
library(readxl)
library(openxlsx)
library(stringr) 
library(animation) 
library(ggplot2)
library(dplyr)
library(KoNLP)
library(tm)
library(wordcloud)
library(RColorBrewer) 
library(RCurl)
library(XML)
library(ggplot2)

# 패키지 설치 종료
print("패키지 설치 완료")
